### ISSUE TITLE
Should PageBot API enable automatic installation of system fonts ?

### ISSUE THREAD

**Issue by felipesanches** [TypeNetwork/PageBot#103]
**Lib/pagebot/fonttoolbox/installfont.py** contains routines for installing fonts on MacOS systems upon requests from user scripts. This is not a cross-platform solution. But before attempting to port this to GNU+Linux, I'd like to discuss whether the ability to install a font is indeed in the scope of PageBot.

I would expect PageBot to use a font file from a relative path of the current user python-script, or to use system-wide available pre-installed fonts. Actually installing new fonts automatically seems to be problematic.

**Comment by felipesanches** [comment]
This is not the same as #98 but certaily a related issue.

**Comment by petrvanblokland** [comment]
The "installing" of fonts is a DrawBot term. They are not actually installed in the system, but just made available in DrawBot. 
To make it platform independent some new functions a added and being tested to find all available fonts in the current platform. The application/script can create a family buy key word and search for fonts in the family: findFamilyByName(familyName), guessFamiliesByPatterns(patterns), family.findFont(...). The resulting Font object can be used in BabelString, independent of platform.
