### ISSUE TITLE
gradient.py syntaxerror

### ISSUE THREAD

**Issue by RenaudFutterer** [TypeNetwork/PageBot#152]
While trying to install pagebot I have the following error on gradient.py line 63 it appears that there is an extra ')'

> Extracting pagebot-0.5-py3.7.egg to /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pagebot-0.5-py3.7.egg/pagebot/gradient.py", line 63
>     assert isinstance(color, Color))
>                                    ^
> SyntaxError: invalid syntax
> 
> Sorry: TabError: inconsistent use of tabs and spaces in indentation (baseapp.py, line 40)

**Comment by michielkauwatjoe** [comment]
You're right, just fixed it.
