### ISSUE TITLE
Small thing: Remove stale branches

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/PageBot#160]
https://github.com/TypeNetwork/PageBot/branches/stale shows a few branches that could perhaps be deleted (as there are 0 commits ahead of master) or no longer relevant (if they are ahead of master)

**Comment by michielkauwatjoe** [comment]
@petrvanblokland I removed the ones that didn't have unique commits, can I remove the other ones as well? (approx. 4-10 commits)

**Comment by michielkauwatjoe** [comment]
Only master and gh-pages are left now.
