### ISSUE TITLE
docs versus Docs (directories)

### ISSUE THREAD

**Issue by felipesanches** [TypeNetwork/PageBot#39]
I wonder why these similarly named directories co-exist at the root of the project tree:

![screenshot at 2017-09-18 17 34 35](https://user-images.githubusercontent.com/213676/30563301-d5dd6092-9c97-11e7-80c5-58e6b6b25b5c.png)

**Comment by petrvanblokland** [comment]
docs is the documentation website, automatically generated from content inside.
@michielkauwatjoe can tell more about that.

**Comment by michielkauwatjoe** [comment]
@felipesanches @petrvanblokland we recently renamed it from docs to Docs; apparently something went wrong. Thanks, I'll see if I can fix it today!

**Comment by davelab6** [comment]
This is likely a Mac OS X case insensitivity issue

**Comment by felipesanches** [comment]
How Insensitive !

https://www.youtube.com/watch?v=uWiL5XuJLQo

**Comment by michielkauwatjoe** [comment]
Should be fixed now, you might need make a new clone if you're on OS X...
