### ISSUE TITLE
How are output targets chosen?

### ISSUE THREAD

**Issue by felipesanches** [TypeNetwork/PageBot#54]
@petrvanblokland I understand that the idea of PageBot is that scripted documents can be automatically translated into many different output formats such as PDF, HTML, PNG, animated-GIFs, etc. And I think that the `pagebot.contexts` are the technical means for implementing these different rendering environments.

I also understand that pagebot contexts are being used to support cross-platform backends (such as drawBot on MacOS and Flat on GNU+Linux).

I've seen code statements on example files explicitly setting up the `defaultContext`. And I've also seen the output being auto-detected by the filename extension used on explicit invocations of the `document.export` method (such as `d.export("ABookCover.pdf")`). So, any scripts doing these things are probably tied to a single possible kind of output? Or am I mixing up different concepts here?

**Comment by felipesanches** [comment]
I think that explicit file formats could (perhaps should?) be avoided and that there could be a way to select the desired output format with a standard set of command line attributes that can be consistently used throughout the codebase (for instance, for all provided examples and also for any user scripts).

Similar to the suggested usage of argparse for the command-line version of "Variables" as described at #44 , there would also be some other form of representation of this feature (providing a means for users to select the desired output format) on other execution environments such as when running on MacOS with drawBot as a backend.

**Comment by felipesanches** [comment]
@petrvanblokland This is something that I've been wondering about.

**Comment by petrvanblokland** [comment]
Same scripts generate all kind of output, depending on the extension of the file. If you do several exports with different file names in DrawBot, then it creates multiple files. Of course the name can be constructed from a selection or loop.

**Comment by felipesanches** [comment]
thanks

**Comment by petrvanblokland** [comment]
See FlatContext.saveDocument(path, multiPage=True) that makes checks on type of document and multipage export. This makes the FlatContext.saveDocument (identical to FlatContext.saveImage) compatible with the existing method in the DrawBotContext.
