### ISSUE TITLE
Setup automated code tests to run on Travis on every pull-request (and on new commits in the master branch)

### ISSUE THREAD

**Issue by felipesanches** [TypeNetwork/PageBot#55]
A caveat is that Travis runs on GNU+Linux, so probably the existing code tests will all fail in the current state of the codebase. And also I don't see how the MacOS-specific portions of the codebase could benefit from automated code tests.

A good thing, on the other hand, is that this can help us gradually improve the quality of the code and move step-by-step in the direction of making it into a cross-platform codebase. I understand that the main developers are developing the code and running it on MacOS, so Travis could complement by testing on a GNU+Linux environment and automatically "raising a flag" when something breaks.

**Comment by anthrotype** [comment]
Travis CI can run on macOS too.

**Comment by justvanrossum** [comment]
Also, DrawBot works "headless" as a module, so non-interactive tests are certainly possible. We actually should set this up for DrawBot itself...

**Comment by felipesanches** [comment]
Thanks! I did not know about that yet :-)

**Comment by felipesanches** [comment]
@petrvanblokland Can you set this up?

https://travis-ci.org/TypeNetwork

![screenshot at 2017-12-07 13 17 02](https://user-images.githubusercontent.com/213676/33722385-ef0386b2-db50-11e7-9472-de8d95112983.png)
